- alias: "Desk LEDs on in the evening"
  trigger:
    platform: time
    at: "17:00:00"
  action:
    service: light.turn_on
    entity_id: light.desk_leds
    data:
      brightness: 128

- alias: "Desk LEDs off at night"
  trigger:
    platform: time
    at: "23:59:00"
  action:
    service: light.turn_off
    entity_id: light.desk_leds